---
default:
  image: 'cr.selcloud.ru/podumai/ci/alpine:1.2'

variables:
  KUBERNETES_CPU_REQUEST: '200m'
  KUBERNETES_CPU_LIMIT: '1000m'
  KUBERNETES_MEMORY_REQUEST: '128Mi'
  KUBERNETES_MEMORY_LIMIT: '256Mi'

stages:
  - 'lint'
  - 'release'

workflow:
  auto_cancel:
    on_new_commit: 'none'
    on_job_failure: 'none'

commit-lint:
  stage: 'lint'
  variables:
    GIT_DEPTH: 0
  before_script:
    - 'pnpm install --frozen-lockfile'
  script:
    - 'pnpm exec commitlint --config commitlint.config.mjs --from HEAD~1 --to HEAD --verbose'

cmake-lint:
  stage: 'lint'
  image: 'astral/uv:0.12'
  needs: [ 'commit-lint' ]
  rules:
    - changes:
        paths:
          - '**/CMakeLists.txt'
          - '**/*.cmake'
  before_script:
    - 'uv sync --frozen'
  script:
    - 'uv run cmake-lint "$CI_PROJECT_DIR/**/CMakeLists.txt" "$CI_PROJECT_DIR/**/*.cmake"'

yaml-lint:
  stage: 'lint'
  image: '$INFRASTRUCTURE_CONTAINER_REGISTRY/ci/yamllint:0.0.3'
  needs: [ 'commit-lint' ]
  rules:
    - changes:
        paths:
          - '**/*.yaml'
          - '**/*.yml'
  script:
    - 'yamllint -c "$CI_PROJECT_DIR/.yamllint.yaml" .'

protobuf-lint:
  stage: 'lint'
  needs: [ 'commit-lint' ]
  rules:
    - changes:
        - 'proto/**/*.proto'
  variables:
    KUBERNETES_CPU_REQUEST: '500m'
    KUBERNETES_CPU_LIMIT: '1800m'

    GOMAXPROCS: 2
  script:
    - 'buf lint --config buf.yaml'

release:
  stage: 'release'
  image: 'node:26.8.2-alpine3.23'
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  variables:
    GIT_DEPTH: 0
  before_script:
    - 'apk add --no-cache git=2.52.0-r0 ca-certificates=20260611-r0'
    # yamllint disable-line
    - >
      npm install -g semantic-release@25.0.9
      @semantic-release/commit-analyzer@13.0.1
      @semantic-release/release-notes-generator@14.1.1
      @semantic-release/changelog@7.0.0
      @semantic-release/git@11.0.1
      @semantic-release/gitlab@13.3.3
      conventional-changelog-conventionalcommits@10.4.0
  script:
    - 'semantic-release'
...
