%YAML 1.2
---
default_install_hook_types: [ 'pre-commit' ]

fail_fast: false

repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: 'v6.0.0'
    hooks:
      - id: 'check-case-conflict'
      - id: 'forbid-submodules'
      - id: 'check-merge-conflict'
      - id: 'end-of-file-fixer'
      - id: 'check-added-large-files'
      - id: 'trailing-whitespace'
        args: [ '--markdown-linebreak-ext=md' ]

  - repo: 'https://github.com/bufbuild/buf'
    rev: 'v1.72.0'
    hooks:
      - id: 'buf-format'
      - id: 'buf-lint'
        args:
          - '--config'
          - 'buf.yaml'

  - repo: 'https://github.com/adrienverge/yamllint.git'
    rev: 'v1.38.0'
    hooks:
      - id: 'yamllint'
        files: '\.(yml|yaml)$'
        args:
          - '-c'
          - '.yamllint.yaml'
          - '--strict'

  - repo: 'https://github.com/betterleaks/betterleaks'
    rev: 'v1.7.4'
    hooks:
      - id: 'betterleaks'

  - repo: 'local'
    hooks:
      - id: 'commitlint'
        name: 'commitlint'
        entry: 'just commitlint'
        language: 'system'
        stages: [ 'commit-msg' ]
        args: [ '--edit' ]
...
