---
branches: [ 'main' ]

tagFormat: 'v${version}'

plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: 'conventional'

  - '@semantic-release/release-notes-generator'

  - - '@semantic-release/changelog'
    - changeLogFile: 'CHANGELOG.md'
      changeLogTitle: '# Changelog'

  - - '@semantic-release/git'
    - assets: [ 'CHANGELOG.md' ]
      message: |
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}

  - - '@semantic-release/gitlab'
    - successComment: false
      failComment: false
...
